name: Spring Boot Docker Image CI

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Setup Docker image name
      id: docker-image-name
      run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          APP_NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)
          echo "app-name = $APP_NAME"

    - name: Login to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASS: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: | 
        echo "image-name = $DOCKER_USER/${{ steps.docker-image-name.outputs.app_name }}:dev"
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        docker build . --file Dockerfile --tag $DOCKER_USER/${{ steps.docker-image-name.outputs.app_name }}:dev

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
