name: Spring Boot Docker Image CI

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Setup Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_REPOSITORY: github-action-sample
      run: |
        docker build -t $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA .
        docker tag $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Push Docker image to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_REPOSITORY: github-action-sample
      run: |
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:$GITHUB_SHA
          docker push $DOCKER_USERNAME/$DOCKER_REPOSITORY:latest
