name: Spring Boot Docker Image CI

on:
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Setup Docker image name
      id: docker-image-name
      run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          APP_NAME=$(mvn help:evaluate -Dexpression=project.name -q -DforceStdout)

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - uses: docker/setup-buildx-action@v1

    - name: Build Docker image and push
      id: build
      uses: docker/build-push-action@v2
      continue-on-error: false
      with:
        context: .
        file: ./Dockerfile
        push: ture
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.docker-image-name.outputs.app_name }}:dev

      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
